name: Check Repositories for about.xml

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main   # Only trigger when pushing to main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install PyGitHub requests

      - name: Run script
        run: |
          source venv/bin/activate
          python check_repos.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_ANDREI }}
